version: "3.2"

services:
  support-postgres:
      image: postgres:latest
      container_name: postgres
      ports:
        - '5432:5432'
      environment:
        - DEBUG=true
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password 
        - POSTGRES_DB=demo
      healthcheck:
        test: ["CMD-SHELL", "pg_isready"]
        interval: 1s
        timeout: 5s
        retries: 10
      networks:
        - support-postgres
      volumes:
        - ./postgres-data:/var/lib/postgresql/data 
      restart: always

networks:
  support-postgres:
